// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: H6KFzMtVnz
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicTableCell.module.css"; // plasmic-import: H6KFzMtVnz/css

export const PlasmicTableCell__VariantProps = new Array("color");

export const PlasmicTableCell__ArgProps = new Array("children");

function PlasmicTableCell__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__color_primaryLight]: hasVariant(
          variants,
          "color",
          "primaryLight"
        ),

        [sty.root__color_primary]: hasVariant(variants, "color", "primary")
      })}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Cell Value",
        value: args.children,
        className: classNames(sty.slotTargetChildren, {
          [sty.slotTargetChildren__color_primary]: hasVariant(
            variants,
            "color",
            "primary"
          )
        })
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTableCell__ArgProps,
      internalVariantPropNames: PlasmicTableCell__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTableCell__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTableCell";
  } else {
    func.displayName = `PlasmicTableCell.${nodeName}`;
  }
  return func;
}

export const PlasmicTableCell = Object.assign(
  // Top-level PlasmicTableCell renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTableCell
    internalVariantProps: PlasmicTableCell__VariantProps,
    internalArgProps: PlasmicTableCell__ArgProps
  }
);

export default PlasmicTableCell;
/* prettier-ignore-end */
