// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: 8aTfxfbh2z
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ListItem from "../../ListItem"; // plasmic-import: T2lyj8FRO_/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicFleetList.module.css"; // plasmic-import: 8aTfxfbh2z/css

export const PlasmicFleetList__VariantProps = new Array();

export const PlasmicFleetList__ArgProps = new Array();

function PlasmicFleetList__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <ListItem
        className={classNames("__wab_instance", sty.listItem__ni7X)}
        componentToRender={"FleetForm"}
        editable={"editable"}
        itemType={"fleet"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__ploZj)}
        componentToRender={"FleetForm"}
        editable={"editable"}
        itemType={"fleet"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem___0IlzA)}
        componentToRender={"FleetForm"}
        editable={"editable"}
        itemType={"fleet"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__czBuu)}
        componentToRender={"FleetForm"}
        editable={"editable"}
        itemType={"fleet"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem___3MaRs)}
        componentToRender={"FleetForm"}
        editable={"editable"}
        itemType={"fleet"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFleetList__ArgProps,
      internalVariantPropNames: PlasmicFleetList__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFleetList__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFleetList";
  } else {
    func.displayName = `PlasmicFleetList.${nodeName}`;
  }
  return func;
}

export const PlasmicFleetList = Object.assign(
  // Top-level PlasmicFleetList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFleetList
    internalVariantProps: PlasmicFleetList__VariantProps,
    internalArgProps: PlasmicFleetList__ArgProps
  }
);

export default PlasmicFleetList;
/* prettier-ignore-end */
