// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: zkmZt9CEr9
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicMuiDialog.module.css"; // plasmic-import: zkmZt9CEr9/css

export const PlasmicMuiDialog__VariantProps = new Array();

export const PlasmicMuiDialog__ArgProps = new Array("children");

function PlasmicMuiDialog__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: null,
        value: args.children
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMuiDialog__ArgProps,
      internalVariantPropNames: PlasmicMuiDialog__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMuiDialog__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMuiDialog";
  } else {
    func.displayName = `PlasmicMuiDialog.${nodeName}`;
  }
  return func;
}

export const PlasmicMuiDialog = Object.assign(
  // Top-level PlasmicMuiDialog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMuiDialog
    internalVariantProps: PlasmicMuiDialog__VariantProps,
    internalArgProps: PlasmicMuiDialog__ArgProps
  }
);

export default PlasmicMuiDialog;
/* prettier-ignore-end */
