// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: Ngfm-OhqRX
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import InputComponent from "../../InputComponent"; // plasmic-import: qNK1ZRC_DP/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicServiceFormFields.module.css"; // plasmic-import: Ngfm-OhqRX/css

export const PlasmicServiceFormFields__VariantProps = new Array();

export const PlasmicServiceFormFields__ArgProps = new Array();

function PlasmicServiceFormFields__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <InputComponent
        data-plasmic-name={"serviceTypeInput"}
        data-plasmic-override={overrides.serviceTypeInput}
        label={"Service Type"}
        type={"select"}
      />

      <InputComponent
        data-plasmic-name={"serviceDepartmentInput"}
        data-plasmic-override={overrides.serviceDepartmentInput}
        className={classNames("__wab_instance", sty.serviceDepartmentInput)}
        label={"Service Department"}
        type={"select"}
      />

      <InputComponent
        data-plasmic-name={"descriptionInput"}
        data-plasmic-override={overrides.descriptionInput}
        className={classNames("__wab_instance", sty.descriptionInput)}
        label={"Description"}
        type={"multiLineText"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "serviceTypeInput",
    "serviceDepartmentInput",
    "descriptionInput"
  ],

  serviceTypeInput: ["serviceTypeInput"],
  serviceDepartmentInput: ["serviceDepartmentInput"],
  descriptionInput: ["descriptionInput"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServiceFormFields__ArgProps,
      internalVariantPropNames: PlasmicServiceFormFields__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicServiceFormFields__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceFormFields";
  } else {
    func.displayName = `PlasmicServiceFormFields.${nodeName}`;
  }
  return func;
}

export const PlasmicServiceFormFields = Object.assign(
  // Top-level PlasmicServiceFormFields renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    serviceTypeInput: makeNodeComponent("serviceTypeInput"),
    serviceDepartmentInput: makeNodeComponent("serviceDepartmentInput"),
    descriptionInput: makeNodeComponent("descriptionInput"),
    // Metadata about props expected for PlasmicServiceFormFields
    internalVariantProps: PlasmicServiceFormFields__VariantProps,
    internalArgProps: PlasmicServiceFormFields__ArgProps
  }
);

export default PlasmicServiceFormFields;
/* prettier-ignore-end */
