// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: i1Lz6JNtIR
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Checkbox from "../../Checkbox"; // plasmic-import: 8Z-pWIumYd5/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicCheckboxInput.module.css"; // plasmic-import: i1Lz6JNtIR/css

export const PlasmicCheckboxInput__VariantProps = new Array();

export const PlasmicCheckboxInput__ArgProps = new Array("children");

function PlasmicCheckboxInput__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Checkbox
        data-plasmic-name={"checkbox"}
        data-plasmic-override={overrides.checkbox}
        className={classNames("__wab_instance", sty.checkbox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Enter some text",
          value: args.children
        })}
      </Checkbox>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "checkbox"],
  checkbox: ["checkbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCheckboxInput__ArgProps,
      internalVariantPropNames: PlasmicCheckboxInput__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicCheckboxInput__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCheckboxInput";
  } else {
    func.displayName = `PlasmicCheckboxInput.${nodeName}`;
  }
  return func;
}

export const PlasmicCheckboxInput = Object.assign(
  // Top-level PlasmicCheckboxInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    checkbox: makeNodeComponent("checkbox"),
    // Metadata about props expected for PlasmicCheckboxInput
    internalVariantProps: PlasmicCheckboxInput__VariantProps,
    internalArgProps: PlasmicCheckboxInput__ArgProps
  }
);

export default PlasmicCheckboxInput;
/* prettier-ignore-end */
