// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: z9IF13sbXf
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import GenericFormComponent from "../../GenericFormComponent"; // plasmic-import: -oqFHJTBGG/component
import FleetFormFields from "../../FleetFormFields"; // plasmic-import: KEWIT-Fk0Z/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicFleetForm.module.css"; // plasmic-import: z9IF13sbXf/css

export const PlasmicFleetForm__VariantProps = new Array();

export const PlasmicFleetForm__ArgProps = new Array();

function PlasmicFleetForm__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <GenericFormComponent
        data-plasmic-name={"genericFormComponent"}
        data-plasmic-override={overrides.genericFormComponent}
        className={classNames("__wab_instance", sty.genericFormComponent)}
        fieldsWrapper={
          <FleetFormFields
            data-plasmic-name={"fleetFormFields"}
            data-plasmic-override={overrides.fleetFormFields}
            className={classNames("__wab_instance", sty.fleetFormFields)}
          />
        }
        redirectOnSubmitLink={"/requests"}
        title={"Add Fleet"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "genericFormComponent", "fleetFormFields"],
  genericFormComponent: ["genericFormComponent", "fleetFormFields"],
  fleetFormFields: ["fleetFormFields"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFleetForm__ArgProps,
      internalVariantPropNames: PlasmicFleetForm__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFleetForm__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFleetForm";
  } else {
    func.displayName = `PlasmicFleetForm.${nodeName}`;
  }
  return func;
}

export const PlasmicFleetForm = Object.assign(
  // Top-level PlasmicFleetForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    genericFormComponent: makeNodeComponent("genericFormComponent"),
    fleetFormFields: makeNodeComponent("fleetFormFields"),
    // Metadata about props expected for PlasmicFleetForm
    internalVariantProps: PlasmicFleetForm__VariantProps,
    internalArgProps: PlasmicFleetForm__ArgProps
  }
);

export default PlasmicFleetForm;
/* prettier-ignore-end */
