// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: 6B1QJB984j-
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Table from "../../Table"; // plasmic-import: sMUya_zWwh/component
import TableRow from "../../TableRow"; // plasmic-import: ivRJDBBaYd/component
import TableCell from "../../TableCell"; // plasmic-import: H6KFzMtVnz/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicFleetByVehicalReport.module.css"; // plasmic-import: 6B1QJB984j-/css

export const PlasmicFleetByVehicalReport__VariantProps = new Array();

export const PlasmicFleetByVehicalReport__ArgProps = new Array();

function PlasmicFleetByVehicalReport__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.text___6XKfn
          )}
        >
          {"Vehical Usage Analysis"}
        </div>
      </div>

      <Table
        data-plasmic-name={"table"}
        data-plasmic-override={overrides.table}
        className={classNames("__wab_instance", sty.table)}
      >
        <TableRow className={classNames("__wab_instance", sty.tableRow__brqUe)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__fTcN)}
            color={"primary"}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__sDa2G
              )}
            >
              {"Vehical"}
            </div>
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__pQgKh)}
            color={"primary"}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__meAs
              )}
            >
              {"Total Duration ( hrs )"}
            </div>
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__x98Qe)}
            color={"primary"}
          >
            {"Day Count"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__ohR37)}
            color={"primary"}
          >
            {"Unique Reservers"}
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__hDuhR)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__rfeGd)}
            color={"primaryLight"}
          >
            {"Honda City"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__lcuhY)}
          >
            {"184"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__nkqMx)}
          >
            {"82"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__ifO)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__bTSsw
              )}
            >
              {"35"}
            </div>
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__mfV12)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__w8VQq)}
            color={"primaryLight"}
          >
            {"Suziki Mehran"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__ix4V1)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___96PZb
              )}
            >
              {"150"}
            </div>
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell___7BxPn)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__l2UE
              )}
            >
              {"67"}
            </div>
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__rE3RB)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__l0Yv3
              )}
            >
              {"44"}
            </div>
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__hyBw)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell___0Xl62)}
            color={"primaryLight"}
          >
            {"Toyota Corolla"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__ffvnO)}
          >
            {"87"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__rJg9D)}
          >
            {"40"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__fsQYw)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__aIuyw
              )}
            >
              {"34"}
            </div>
          </TableCell>
        </TableRow>
      </Table>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "table"],
  freeBox: ["freeBox"],
  table: ["table"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFleetByVehicalReport__ArgProps,
      internalVariantPropNames: PlasmicFleetByVehicalReport__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFleetByVehicalReport__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFleetByVehicalReport";
  } else {
    func.displayName = `PlasmicFleetByVehicalReport.${nodeName}`;
  }
  return func;
}

export const PlasmicFleetByVehicalReport = Object.assign(
  // Top-level PlasmicFleetByVehicalReport renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    table: makeNodeComponent("table"),
    // Metadata about props expected for PlasmicFleetByVehicalReport
    internalVariantProps: PlasmicFleetByVehicalReport__VariantProps,
    internalArgProps: PlasmicFleetByVehicalReport__ArgProps
  }
);

export default PlasmicFleetByVehicalReport;
/* prettier-ignore-end */
