// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: YYWHj4LFug
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import AdminLayout from "../../AdminLayout"; // plasmic-import: 046Osy-48bS/component
import Sidebar from "../../Sidebar"; // plasmic-import: 2ETjiGbh3p/component
import ServiceByPersonServiceTypeReport from "../../ServiceByPersonServiceTypeReport"; // plasmic-import: uiePGwqQNc/component
import ServiceByTypeReport from "../../ServiceByTypeReport"; // plasmic-import: PTiYGP8uYr/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicAdminReportsService.module.css"; // plasmic-import: YYWHj4LFug/css

export const PlasmicAdminReportsService__VariantProps = new Array();

export const PlasmicAdminReportsService__ArgProps = new Array();

function PlasmicAdminReportsService__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      >
        <AdminLayout
          data-plasmic-name={"adminLayout"}
          data-plasmic-override={overrides.adminLayout}
          breadcrumbs={
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text
              )}
            >
              {"Reports"}
            </div>
          }
          className={classNames("__wab_instance", sty.adminLayout)}
          hideAddButton={"hideAddButton"}
          mainWrapper={
            <p.Stack
              as={"div"}
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox)}
            >
              <ServiceByPersonServiceTypeReport
                data-plasmic-name={"serviceByPersonServiceTypeReport"}
                data-plasmic-override={
                  overrides.serviceByPersonServiceTypeReport
                }
                className={classNames(
                  "__wab_instance",
                  sty.serviceByPersonServiceTypeReport
                )}
              />

              <ServiceByTypeReport
                data-plasmic-name={"serviceByTypeReport"}
                data-plasmic-override={overrides.serviceByTypeReport}
                className={classNames(
                  "__wab_instance",
                  sty.serviceByTypeReport
                )}
              />
            </p.Stack>
          }
          type={"reporting"}
        >
          <Sidebar
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            admin={"admin"}
            className={classNames("__wab_instance", sty.sidebar)}
          />
        </AdminLayout>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "adminLayout",
    "sidebar",
    "text",
    "freeBox",
    "serviceByPersonServiceTypeReport",
    "serviceByTypeReport"
  ],

  adminLayout: [
    "adminLayout",
    "sidebar",
    "text",
    "freeBox",
    "serviceByPersonServiceTypeReport",
    "serviceByTypeReport"
  ],

  sidebar: ["sidebar"],
  text: ["text"],
  freeBox: [
    "freeBox",
    "serviceByPersonServiceTypeReport",
    "serviceByTypeReport"
  ],

  serviceByPersonServiceTypeReport: ["serviceByPersonServiceTypeReport"],
  serviceByTypeReport: ["serviceByTypeReport"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAdminReportsService__ArgProps,
      internalVariantPropNames: PlasmicAdminReportsService__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicAdminReportsService__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdminReportsService";
  } else {
    func.displayName = `PlasmicAdminReportsService.${nodeName}`;
  }
  return func;
}

export const PlasmicAdminReportsService = Object.assign(
  // Top-level PlasmicAdminReportsService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    adminLayout: makeNodeComponent("adminLayout"),
    sidebar: makeNodeComponent("sidebar"),
    text: makeNodeComponent("text"),
    freeBox: makeNodeComponent("freeBox"),
    serviceByPersonServiceTypeReport: makeNodeComponent(
      "serviceByPersonServiceTypeReport"
    ),

    serviceByTypeReport: makeNodeComponent("serviceByTypeReport"),
    // Metadata about props expected for PlasmicAdminReportsService
    internalVariantProps: PlasmicAdminReportsService__VariantProps,
    internalArgProps: PlasmicAdminReportsService__ArgProps
  }
);

export default PlasmicAdminReportsService;
/* prettier-ignore-end */
