// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: eQfqLbonTV
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicMultiLineTextInput.module.css"; // plasmic-import: eQfqLbonTV/css

export const PlasmicMultiLineTextInput__VariantProps = new Array();

export const PlasmicMultiLineTextInput__ArgProps = new Array();

function PlasmicMultiLineTextInput__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <textarea
        data-plasmic-name={"textarea"}
        data-plasmic-override={overrides.textarea}
        className={classNames(defaultcss.textarea, sty.textarea)}
        value={""}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textarea"],
  textarea: ["textarea"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMultiLineTextInput__ArgProps,
      internalVariantPropNames: PlasmicMultiLineTextInput__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMultiLineTextInput__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMultiLineTextInput";
  } else {
    func.displayName = `PlasmicMultiLineTextInput.${nodeName}`;
  }
  return func;
}

export const PlasmicMultiLineTextInput = Object.assign(
  // Top-level PlasmicMultiLineTextInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textarea: makeNodeComponent("textarea"),
    // Metadata about props expected for PlasmicMultiLineTextInput
    internalVariantProps: PlasmicMultiLineTextInput__VariantProps,
    internalArgProps: PlasmicMultiLineTextInput__ArgProps
  }
);

export default PlasmicMultiLineTextInput;
/* prettier-ignore-end */
