// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: c0wjAX7GRT
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ListItem from "../../ListItem"; // plasmic-import: T2lyj8FRO_/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicServicesList.module.css"; // plasmic-import: c0wjAX7GRT/css

export const PlasmicServicesList__VariantProps = new Array();

export const PlasmicServicesList__ArgProps = new Array();

function PlasmicServicesList__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <ListItem
        className={classNames("__wab_instance", sty.listItem___80Ood)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem___131X9)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__lzs2Z)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__lEmPf)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__b3S)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__sIAwl)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__fZaQj)}
        componentToRender={"ServiceForm"}
        editable={"editable"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServicesList__ArgProps,
      internalVariantPropNames: PlasmicServicesList__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicServicesList__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServicesList";
  } else {
    func.displayName = `PlasmicServicesList.${nodeName}`;
  }
  return func;
}

export const PlasmicServicesList = Object.assign(
  // Top-level PlasmicServicesList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicServicesList
    internalVariantProps: PlasmicServicesList__VariantProps,
    internalArgProps: PlasmicServicesList__ArgProps
  }
);

export default PlasmicServicesList;
/* prettier-ignore-end */
