// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: pW2-Z0pIhy
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import AdminLayout from "../../AdminLayout"; // plasmic-import: 046Osy-48bS/component
import Sidebar from "../../Sidebar"; // plasmic-import: 2ETjiGbh3p/component
import RequestList from "../../RequestList"; // plasmic-import: R7-uUmA8YC/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicAdminDashboard.module.css"; // plasmic-import: pW2-Z0pIhy/css

export const PlasmicAdminDashboard__VariantProps = new Array();

export const PlasmicAdminDashboard__ArgProps = new Array();

function PlasmicAdminDashboard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <AdminLayout
            data-plasmic-name={"adminLayout"}
            data-plasmic-override={overrides.adminLayout}
            breadcrumbs={
              <React.Fragment>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__oTyKs
                  )}
                >
                  {"Approvals"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__s9RCw
                  )}
                >
                  {">"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__otpdm
                  )}
                >
                  {"List"}
                </div>
              </React.Fragment>
            }
            className={classNames("__wab_instance", sty.adminLayout)}
            hideAddButton={"hideAddButton"}
            mainWrapper={
              <RequestList
                data-plasmic-name={"requestList"}
                data-plasmic-override={overrides.requestList}
                className={classNames("__wab_instance", sty.requestList)}
              />
            }
          >
            <Sidebar
              data-plasmic-name={"sidebar"}
              data-plasmic-override={overrides.sidebar}
              admin={"admin"}
              className={classNames("__wab_instance", sty.sidebar)}
            />
          </AdminLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "adminLayout", "sidebar", "requestList"],
  adminLayout: ["adminLayout", "sidebar", "requestList"],
  sidebar: ["sidebar"],
  requestList: ["requestList"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAdminDashboard__ArgProps,
      internalVariantPropNames: PlasmicAdminDashboard__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicAdminDashboard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdminDashboard";
  } else {
    func.displayName = `PlasmicAdminDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicAdminDashboard = Object.assign(
  // Top-level PlasmicAdminDashboard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    adminLayout: makeNodeComponent("adminLayout"),
    sidebar: makeNodeComponent("sidebar"),
    requestList: makeNodeComponent("requestList"),
    // Metadata about props expected for PlasmicAdminDashboard
    internalVariantProps: PlasmicAdminDashboard__VariantProps,
    internalArgProps: PlasmicAdminDashboard__ArgProps
  }
);

export default PlasmicAdminDashboard;
/* prettier-ignore-end */
