// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: ivRJDBBaYd
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TableCell from "../../TableCell"; // plasmic-import: H6KFzMtVnz/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicTableRow.module.css"; // plasmic-import: ivRJDBBaYd/css

export const PlasmicTableRow__VariantProps = new Array();

export const PlasmicTableRow__ArgProps = new Array("children");

function PlasmicTableRow__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <React.Fragment>
            <TableCell
              className={classNames("__wab_instance", sty.tableCell__cpsn)}
            />

            <TableCell
              className={classNames("__wab_instance", sty.tableCell__meZs9)}
            />

            <TableCell
              className={classNames("__wab_instance", sty.tableCell__ua29M)}
            />
          </React.Fragment>
        ),

        value: args.children
      })}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTableRow__ArgProps,
      internalVariantPropNames: PlasmicTableRow__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTableRow__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTableRow";
  } else {
    func.displayName = `PlasmicTableRow.${nodeName}`;
  }
  return func;
}

export const PlasmicTableRow = Object.assign(
  // Top-level PlasmicTableRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTableRow
    internalVariantProps: PlasmicTableRow__VariantProps,
    internalArgProps: PlasmicTableRow__ArgProps
  }
);

export default PlasmicTableRow;
/* prettier-ignore-end */
