// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: CK5bncNDH9
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import UserLayout from "../../UserLayout"; // plasmic-import: TF4eeP5pkV/component
import MeetingRoomList from "../../MeetingRoomList"; // plasmic-import: trbmvASZWn/component
import Sidebar from "../../Sidebar"; // plasmic-import: 2ETjiGbh3p/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicMeetingRoomsPage.module.css"; // plasmic-import: CK5bncNDH9/css

export const PlasmicMeetingRoomsPage__VariantProps = new Array();

export const PlasmicMeetingRoomsPage__ArgProps = new Array();

function PlasmicMeetingRoomsPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      >
        <UserLayout
          data-plasmic-name={"userLayout"}
          data-plasmic-override={overrides.userLayout}
          breadcrumbs={
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__xjg02
                )}
              >
                {"Meeting Roooms"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text___5DMwI
                )}
              >
                {">"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__u9PCp
                )}
              >
                {"List"}
              </div>
            </React.Fragment>
          }
          className={classNames("__wab_instance", sty.userLayout)}
          mainWrapper={
            <MeetingRoomList
              data-plasmic-name={"meetingRoomList"}
              data-plasmic-override={overrides.meetingRoomList}
              className={classNames("__wab_instance", sty.meetingRoomList)}
            />
          }
        >
          <Sidebar
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            className={classNames("__wab_instance", sty.sidebar)}
          />
        </UserLayout>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "userLayout", "meetingRoomList", "sidebar"],
  userLayout: ["userLayout", "meetingRoomList", "sidebar"],
  meetingRoomList: ["meetingRoomList"],
  sidebar: ["sidebar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMeetingRoomsPage__ArgProps,
      internalVariantPropNames: PlasmicMeetingRoomsPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMeetingRoomsPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMeetingRoomsPage";
  } else {
    func.displayName = `PlasmicMeetingRoomsPage.${nodeName}`;
  }
  return func;
}

export const PlasmicMeetingRoomsPage = Object.assign(
  // Top-level PlasmicMeetingRoomsPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    userLayout: makeNodeComponent("userLayout"),
    meetingRoomList: makeNodeComponent("meetingRoomList"),
    sidebar: makeNodeComponent("sidebar"),
    // Metadata about props expected for PlasmicMeetingRoomsPage
    internalVariantProps: PlasmicMeetingRoomsPage__VariantProps,
    internalArgProps: PlasmicMeetingRoomsPage__ArgProps
  }
);

export default PlasmicMeetingRoomsPage;
/* prettier-ignore-end */
