// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: uiePGwqQNc
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Table from "../../Table"; // plasmic-import: sMUya_zWwh/component
import TableRow from "../../TableRow"; // plasmic-import: ivRJDBBaYd/component
import TableCell from "../../TableCell"; // plasmic-import: H6KFzMtVnz/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicServiceByPersonServiceTypeReport.module.css"; // plasmic-import: uiePGwqQNc/css

export const PlasmicServiceByPersonServiceTypeReport__VariantProps =
  new Array();

export const PlasmicServiceByPersonServiceTypeReport__ArgProps = new Array();

function PlasmicServiceByPersonServiceTypeReport__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.text__e4XOj
          )}
        >
          {"Person/Service Type  Analysis"}
        </div>
      </div>

      <Table
        data-plasmic-name={"table"}
        data-plasmic-override={overrides.table}
        className={classNames("__wab_instance", sty.table)}
      >
        <TableRow className={classNames("__wab_instance", sty.tableRow__eDpYe)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__aiQqi)}
            color={"primary"}
          >
            {"Person"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__lxED)}
            color={"primary"}
          >
            {"Service Type"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__d6Mt)}
            color={"primary"}
          >
            {"Count"}
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__zkyMt)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__xp4Hj)}
            color={"primaryLight"}
          >
            {"Ali Hussain"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__mo7BL)}
            color={"primaryLight"}
          >
            {"Plumbing"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__zUas)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text___3IIct
              )}
            >
              {"20"}
            </div>
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__xs9Cb)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__yqbI)}
            color={"primaryLight"}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__jicnV
              )}
            >
              {"Faizan Shabbir"}
            </div>
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__r3T4N)}
            color={"primaryLight"}
          >
            {"Electronics"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__if2Vt)}
          >
            {"15"}
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__pXtcU)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__bhPe1)}
            color={"primaryLight"}
          >
            {"Ibtisaam"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__p4KFw)}
            color={"primaryLight"}
          >
            {"Electronics"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__zw02N)}
          >
            {"5"}
          </TableCell>
        </TableRow>

        <TableRow className={classNames("__wab_instance", sty.tableRow__taBd)}>
          <TableCell
            className={classNames("__wab_instance", sty.tableCell__j00Ue)}
            color={"primaryLight"}
          >
            {"Yasir"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__d4QFu)}
            color={"primaryLight"}
          >
            {"Plumbing"}
          </TableCell>

          <TableCell
            className={classNames("__wab_instance", sty.tableCell__cpPMe)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__il2Rh
              )}
            >
              {"4"}
            </div>
          </TableCell>
        </TableRow>
      </Table>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "table"],
  freeBox: ["freeBox"],
  table: ["table"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServiceByPersonServiceTypeReport__ArgProps,
      internalVariantPropNames:
        PlasmicServiceByPersonServiceTypeReport__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicServiceByPersonServiceTypeReport__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceByPersonServiceTypeReport";
  } else {
    func.displayName = `PlasmicServiceByPersonServiceTypeReport.${nodeName}`;
  }
  return func;
}

export const PlasmicServiceByPersonServiceTypeReport = Object.assign(
  // Top-level PlasmicServiceByPersonServiceTypeReport renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    table: makeNodeComponent("table"),
    // Metadata about props expected for PlasmicServiceByPersonServiceTypeReport
    internalVariantProps: PlasmicServiceByPersonServiceTypeReport__VariantProps,
    internalArgProps: PlasmicServiceByPersonServiceTypeReport__ArgProps
  }
);

export default PlasmicServiceByPersonServiceTypeReport;
/* prettier-ignore-end */
