// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: trbmvASZWn
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import ListItem from "../../ListItem"; // plasmic-import: T2lyj8FRO_/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicMeetingRoomList.module.css"; // plasmic-import: trbmvASZWn/css

export const PlasmicMeetingRoomList__VariantProps = new Array();

export const PlasmicMeetingRoomList__ArgProps = new Array();

function PlasmicMeetingRoomList__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <ListItem
        className={classNames("__wab_instance", sty.listItem__wIjU6)}
        componentToRender={"MeetingRoomForm"}
        editable={"editable"}
        itemType={"meetingRoom"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem___8Pfue)}
        componentToRender={"MeetingRoomForm"}
        editable={"editable"}
        itemType={"meetingRoom"}
      />

      <ListItem
        className={classNames("__wab_instance", sty.listItem__wkz8Q)}
        componentToRender={"MeetingRoomForm"}
        editable={"editable"}
        itemType={"meetingRoom"}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMeetingRoomList__ArgProps,
      internalVariantPropNames: PlasmicMeetingRoomList__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMeetingRoomList__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMeetingRoomList";
  } else {
    func.displayName = `PlasmicMeetingRoomList.${nodeName}`;
  }
  return func;
}

export const PlasmicMeetingRoomList = Object.assign(
  // Top-level PlasmicMeetingRoomList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMeetingRoomList
    internalVariantProps: PlasmicMeetingRoomList__VariantProps,
    internalArgProps: PlasmicMeetingRoomList__ArgProps
  }
);

export default PlasmicMeetingRoomList;
/* prettier-ignore-end */
