// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: gLEeJSAqSz
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import UserLayout from "../../UserLayout"; // plasmic-import: TF4eeP5pkV/component
import ProfilePageComponent from "../../ProfilePageComponent"; // plasmic-import: xwDhpOnB24/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicUserProfilePage.module.css"; // plasmic-import: gLEeJSAqSz/css

export const PlasmicUserProfilePage__VariantProps = new Array();

export const PlasmicUserProfilePage__ArgProps = new Array();

function PlasmicUserProfilePage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      >
        <UserLayout
          data-plasmic-name={"userLayout"}
          data-plasmic-override={overrides.userLayout}
          breadcrumbs={
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__dKm7D
                )}
              >
                {"User"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__w27Jv
                )}
              >
                {">"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__bP5D
                )}
              >
                {"Profile"}
              </div>
            </React.Fragment>
          }
          className={classNames("__wab_instance", sty.userLayout)}
          hideFilters={"hideFilters"}
          mainWrapper={
            <ProfilePageComponent
              data-plasmic-name={"profilePageComponent"}
              data-plasmic-override={overrides.profilePageComponent}
              className={classNames("__wab_instance", sty.profilePageComponent)}
            />
          }
        />
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "userLayout", "profilePageComponent"],
  userLayout: ["userLayout", "profilePageComponent"],
  profilePageComponent: ["profilePageComponent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUserProfilePage__ArgProps,
      internalVariantPropNames: PlasmicUserProfilePage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicUserProfilePage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserProfilePage";
  } else {
    func.displayName = `PlasmicUserProfilePage.${nodeName}`;
  }
  return func;
}

export const PlasmicUserProfilePage = Object.assign(
  // Top-level PlasmicUserProfilePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    userLayout: makeNodeComponent("userLayout"),
    profilePageComponent: makeNodeComponent("profilePageComponent"),
    // Metadata about props expected for PlasmicUserProfilePage
    internalVariantProps: PlasmicUserProfilePage__VariantProps,
    internalArgProps: PlasmicUserProfilePage__ArgProps
  }
);

export default PlasmicUserProfilePage;
/* prettier-ignore-end */
