// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: rHmoMrEiAJ
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import AdminLayout from "../../AdminLayout"; // plasmic-import: 046Osy-48bS/component
import ProfilePageComponent from "../../ProfilePageComponent"; // plasmic-import: xwDhpOnB24/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicAdminProfilePage.module.css"; // plasmic-import: rHmoMrEiAJ/css

export const PlasmicAdminProfilePage__VariantProps = new Array();

export const PlasmicAdminProfilePage__ArgProps = new Array();

function PlasmicAdminProfilePage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      >
        <AdminLayout
          data-plasmic-name={"adminLayout"}
          data-plasmic-override={overrides.adminLayout}
          breadcrumbs={
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__e0PWi
                )}
              >
                {"Admin"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__dhCuw
                )}
              >
                {">"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__pOi7D
                )}
              >
                {"Profile"}
              </div>
            </React.Fragment>
          }
          className={classNames("__wab_instance", sty.adminLayout)}
          hideAddButton={"hideAddButton"}
          hideFilters={"hideFilters"}
          mainWrapper={
            <ProfilePageComponent
              data-plasmic-name={"profilePageComponent"}
              data-plasmic-override={overrides.profilePageComponent}
              className={classNames("__wab_instance", sty.profilePageComponent)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__ooTb0
                )}
              >
                {"Admin User"}
              </div>
            </ProfilePageComponent>
          }
        />
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "adminLayout", "profilePageComponent"],
  adminLayout: ["adminLayout", "profilePageComponent"],
  profilePageComponent: ["profilePageComponent"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAdminProfilePage__ArgProps,
      internalVariantPropNames: PlasmicAdminProfilePage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicAdminProfilePage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdminProfilePage";
  } else {
    func.displayName = `PlasmicAdminProfilePage.${nodeName}`;
  }
  return func;
}

export const PlasmicAdminProfilePage = Object.assign(
  // Top-level PlasmicAdminProfilePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    adminLayout: makeNodeComponent("adminLayout"),
    profilePageComponent: makeNodeComponent("profilePageComponent"),
    // Metadata about props expected for PlasmicAdminProfilePage
    internalVariantProps: PlasmicAdminProfilePage__VariantProps,
    internalArgProps: PlasmicAdminProfilePage__ArgProps
  }
);

export default PlasmicAdminProfilePage;
/* prettier-ignore-end */
