// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: wbI2f6rjYF
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: gb4IIit3yv/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicTimeRangeInput.module.css"; // plasmic-import: wbI2f6rjYF/css

export const PlasmicTimeRangeInput__VariantProps = new Array();

export const PlasmicTimeRangeInput__ArgProps = new Array();

function PlasmicTimeRangeInput__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <TextInput
        data-plasmic-name={"textInput"}
        data-plasmic-override={overrides.textInput}
        className={classNames("__wab_instance", sty.textInput)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput"],
  textInput: ["textInput"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTimeRangeInput__ArgProps,
      internalVariantPropNames: PlasmicTimeRangeInput__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicTimeRangeInput__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTimeRangeInput";
  } else {
    func.displayName = `PlasmicTimeRangeInput.${nodeName}`;
  }
  return func;
}

export const PlasmicTimeRangeInput = Object.assign(
  // Top-level PlasmicTimeRangeInput renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    // Metadata about props expected for PlasmicTimeRangeInput
    internalVariantProps: PlasmicTimeRangeInput__VariantProps,
    internalArgProps: PlasmicTimeRangeInput__ArgProps
  }
);

export default PlasmicTimeRangeInput;
/* prettier-ignore-end */
