// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiynbYDu6GiGaNNDvPQoVR
// Component: abJRRipQu8
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import UserLayout from "../../UserLayout"; // plasmic-import: TF4eeP5pkV/component
import FleetForm from "../../FleetForm"; // plasmic-import: z9IF13sbXf/component
import Sidebar from "../../Sidebar"; // plasmic-import: 2ETjiGbh3p/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: iiynbYDu6GiGaNNDvPQoVR/projectcss
import * as sty from "./PlasmicFleetPage.module.css"; // plasmic-import: abJRRipQu8/css

export const PlasmicFleetPage__VariantProps = new Array();

export const PlasmicFleetPage__ArgProps = new Array();

function PlasmicFleetPage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
      >
        <UserLayout
          data-plasmic-name={"userLayout"}
          data-plasmic-override={overrides.userLayout}
          breadcrumbs={
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__kQ2A9
                )}
              >
                {"Fleet"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__wlZve
                )}
              >
                {">"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__dBttD
                )}
              >
                {"Add Fleet"}
              </div>
            </React.Fragment>
          }
          className={classNames("__wab_instance", sty.userLayout)}
          hideFilters={"hideFilters"}
          mainWrapper={
            <FleetForm
              data-plasmic-name={"fleetForm"}
              data-plasmic-override={overrides.fleetForm}
              className={classNames("__wab_instance", sty.fleetForm)}
            />
          }
        >
          <Sidebar
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            className={classNames("__wab_instance", sty.sidebar)}
          />
        </UserLayout>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "userLayout", "fleetForm", "sidebar"],
  userLayout: ["userLayout", "fleetForm", "sidebar"],
  fleetForm: ["fleetForm"],
  sidebar: ["sidebar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFleetPage__ArgProps,
      internalVariantPropNames: PlasmicFleetPage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFleetPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFleetPage";
  } else {
    func.displayName = `PlasmicFleetPage.${nodeName}`;
  }
  return func;
}

export const PlasmicFleetPage = Object.assign(
  // Top-level PlasmicFleetPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    userLayout: makeNodeComponent("userLayout"),
    fleetForm: makeNodeComponent("fleetForm"),
    sidebar: makeNodeComponent("sidebar"),
    // Metadata about props expected for PlasmicFleetPage
    internalVariantProps: PlasmicFleetPage__VariantProps,
    internalArgProps: PlasmicFleetPage__ArgProps
  }
);

export default PlasmicFleetPage;
/* prettier-ignore-end */
